### ISSUE TITLE
generate the SDK with added openAPI spec (plugins) ?

### ISSUE THREAD

**Issue by zyxep** [smutel/go-netbox#57]
Hey,

I am using the SDK quite a bit right now and in my own instance of Netbox I have added a plugin (netbox_gateways).
It has generated Swagger spec, how can i generate SDK to use that?

**Comment by smutel** [comment]
Hello,

I don't know if you have a separated swagger for the plugin or swagger of the plugin is added to the main netbox swagger ?
You can anyway look at this [script](../blob/main/utils/netbox_generate_client) and use it with the swagger of your Netbox instance.

Regards,

**Comment by zyxep** [comment]
The plugin does have swagger and i see the docs in my own docs instance that it was there.
I had to "heavily" modify the script a little bit because i am on macbook pro (m1 max).
When i got it to generate the SDK i found that some maxInt was failing 😂  so basically last night i went on my linux VPS server and triggered the script.

I can report that there is a difference between v3.3 & v3.4, i think it might reapply netbox own version of e.g. availableIP's 🤔
