### ISSUE TITLE
constant 9223372036854776000 overflows int64

### ISSUE THREAD

**Issue by chrissnell-okta** [smutel/go-netbox#8]
Trying to build a simple project that fetches some IPAM prefixes and one of models tests is causing an error:

```
% go build
# github.com/smutel/go-netbox/netbox/models
vendor/github.com/smutel/go-netbox/netbox/models/v_l_a_n_group.go:197:64: constant 9223372036854776000 overflows int64
```

I'm guessing that int64 should be a float64?

Also, shouldn't the import on your first example in the README be `github.com/smutel/go-netbox/netbox/client`?

**Comment by smutel** [comment]
I am aware of this issue witch is due to a wrong swagger def in netbox.  
Currently improving the project to be able to patch the swagger before generating the lib (to not be linked to the netbox project).

**Comment by smutel** [comment]
I made a workaround in the last MR: https://github.com/smutel/go-netbox/blob/main/patchs/swagger-v2.11.12-vlangroup-maxint.patch.
